import React, { createContext, useContext, useState, useCallback } from "react";

export type Lang = "fr" | "en" | "ar";

const translations: Record<Lang, Record<string, string>> = {
  fr: {
    // Nav
    "nav.home": "Accueil",
    "nav.catalog": "Catalogue",
    "nav.accounts": "Comptes",
    "nav.giftCards": "Cartes Cadeaux",
    "nav.login": "Connexion",
    "nav.logout": "Déconnexion",
    "nav.myOrders": "Mes Commandes",
    "nav.admin": "Admin",
    // Index
    "home.instantDelivery": "Livraison Instantanée",
    "home.instantDeliveryDesc": "Recevez votre produit en quelques minutes",
    "home.securePayment": "Paiement Sécurisé",
    "home.securePaymentDesc": "WafaCash, CashPlus, Virement bancaire",
    "home.support247": "Support 24/7",
    "home.support247Desc": "Assistance par WhatsApp et Telegram",
    "home.categories": "Catégories",
    "home.trending": "🔥 Tendances",
    "home.bestSellers": "⭐ Meilleures Ventes",
    "home.viewAll": "Voir tout",
    "home.joinTitle": "Rejoignez Zuoss Shop",
    "home.joinDesc": "Créez votre compte et profitez de nos offres exclusives sur les jeux numériques au Maroc.",
    "home.exploreCatalog": "Explorer le catalogue",
    // Catalog
    "catalog.title": "Catalogue",
    "catalog.subtitle": "Découvrez nos jeux et produits numériques",
    "catalog.search": "Rechercher un jeu...",
    "catalog.filters": "Filtres",
    "catalog.platform": "Plateforme",
    "catalog.category": "Catégorie",
    "catalog.price": "Prix",
    "catalog.clearFilters": "Effacer les filtres",
    "catalog.results": "résultat(s)",
    "catalog.noProducts": "Aucun produit trouvé",
    "catalog.resetFilters": "Réinitialiser les filtres",
    "catalog.sortBy": "Trier par",
    "catalog.sortDefault": "Par défaut",
    "catalog.sortPriceLow": "Prix croissant",
    "catalog.sortPriceHigh": "Prix décroissant",
    "catalog.sortRating": "Meilleures notes",
    "catalog.sortNewest": "Plus récents",
    "catalog.inStockOnly": "En stock uniquement",
    // Product
    "product.back": "Retour au catalogue",
    "product.notFound": "Produit non trouvé",
    "product.loading": "Chargement...",
    "product.type": "Type",
    "product.delivery": "Livraison",
    "product.stock": "Stock",
    "product.inStock": "En stock",
    "product.outOfStock": "Épuisé",
    "product.instant": "Instantanée",
    "product.addToCart": "Ajouter au panier",
    "product.addedToCart": "Ajouté au panier",
    "product.instructions": "📋 Instructions",
    "product.relatedProducts": "Produits similaires",
    "product.reviews": "avis",
    "product.account": "Compte complet",
    "product.key": "Clé d'activation",
    // Reviews
    "reviews.title": "Avis clients",
    "reviews.writeReview": "Écrire un avis",
    "reviews.submitReview": "Publier l'avis",
    "reviews.noReviews": "Aucun avis pour le moment. Soyez le premier !",
    "reviews.loginToReview": "Connectez-vous pour laisser un avis",
    "reviews.placeholder": "Partagez votre expérience...",
    // Cart
    "cart.title": "Panier",
    "cart.empty": "Votre panier est vide",
    "cart.browseCatalog": "Parcourir le catalogue",
    "cart.subtotal": "Sous-total",
    "cart.shipping": "Frais",
    "cart.free": "Gratuit",
    "cart.total": "Total",
    "cart.checkout": "Commander",
    "cart.clear": "Vider le panier",
    // Checkout
    "checkout.title": "Finaliser la commande",
    "checkout.backToCart": "Retour au panier",
    "checkout.paymentMethod": "Mode de paiement",
    "checkout.paymentProof": "Preuve de paiement",
    "checkout.uploadProof": "Cliquez ou glissez le reçu ici",
    "checkout.uploadFormat": "PNG, JPG ou PDF (max 5 Mo)",
    "checkout.notes": "Notes (optionnel)",
    "checkout.notesPlaceholder": "Informations supplémentaires...",
    "checkout.summary": "Résumé",
    "checkout.discount": "Réduction",
    "checkout.confirm": "Confirmer la commande",
    "checkout.sending": "Envoi en cours...",
    "checkout.deliveryNote": "Livraison instantanée après vérification du paiement",
    "checkout.success": "Commande confirmée !",
    "checkout.successDesc": "Votre commande a été envoyée avec succès. Nous allons vérifier votre paiement et vous livrer vos produits.",
    "checkout.successEmail": "Vous recevrez vos identifiants par email une fois le paiement vérifié.",
    "checkout.continueShopping": "Continuer vos achats",
    // Footer
    "footer.desc": "Votre boutique de jeux numériques au Maroc. Comptes, clés et cartes cadeaux pour toutes les plateformes.",
    "footer.navigation": "Navigation",
    "footer.platforms": "Plateformes",
    "footer.contact": "Contact",
    "footer.rights": "Tous droits réservés.",
    // Orders
    "orders.title": "Mes Commandes",
    "orders.noOrders": "Aucune commande pour le moment",
    "orders.discoverCatalog": "Découvrir le catalogue",
    "orders.orderFrom": "Commande du",
    "orders.payment": "Paiement",
    "orders.code": "Code",
    "orders.pending": "En attente",
    "orders.confirmed": "Confirmée",
    "orders.delivered": "Livrée",
    "orders.cancelled": "Annulée",
    // Auth
    "auth.back": "Retour",
    // Common
    "common.back": "Retour",
  },
  en: {
    "nav.home": "Home",
    "nav.catalog": "Catalog",
    "nav.accounts": "Accounts",
    "nav.giftCards": "Gift Cards",
    "nav.login": "Login",
    "nav.logout": "Log out",
    "nav.myOrders": "My Orders",
    "nav.admin": "Admin",
    "home.instantDelivery": "Instant Delivery",
    "home.instantDeliveryDesc": "Receive your product in minutes",
    "home.securePayment": "Secure Payment",
    "home.securePaymentDesc": "WafaCash, CashPlus, Bank Transfer",
    "home.support247": "24/7 Support",
    "home.support247Desc": "Help via WhatsApp and Telegram",
    "home.categories": "Categories",
    "home.trending": "🔥 Trending",
    "home.bestSellers": "⭐ Best Sellers",
    "home.viewAll": "View all",
    "home.joinTitle": "Join Zuoss Shop",
    "home.joinDesc": "Create your account and enjoy exclusive offers on digital games in Morocco.",
    "home.exploreCatalog": "Explore Catalog",
    "catalog.title": "Catalog",
    "catalog.subtitle": "Discover our games and digital products",
    "catalog.search": "Search for a game...",
    "catalog.filters": "Filters",
    "catalog.platform": "Platform",
    "catalog.category": "Category",
    "catalog.price": "Price",
    "catalog.clearFilters": "Clear filters",
    "catalog.results": "result(s)",
    "catalog.noProducts": "No products found",
    "catalog.resetFilters": "Reset filters",
    "catalog.sortBy": "Sort by",
    "catalog.sortDefault": "Default",
    "catalog.sortPriceLow": "Price: Low to High",
    "catalog.sortPriceHigh": "Price: High to Low",
    "catalog.sortRating": "Top Rated",
    "catalog.sortNewest": "Newest",
    "catalog.inStockOnly": "In stock only",
    "product.back": "Back to catalog",
    "product.notFound": "Product not found",
    "product.loading": "Loading...",
    "product.type": "Type",
    "product.delivery": "Delivery",
    "product.stock": "Stock",
    "product.inStock": "In stock",
    "product.outOfStock": "Out of stock",
    "product.instant": "Instant",
    "product.addToCart": "Add to cart",
    "product.addedToCart": "Added to cart",
    "product.instructions": "📋 Instructions",
    "product.relatedProducts": "Related products",
    "product.reviews": "reviews",
    "product.account": "Full account",
    "product.key": "Activation key",
    "reviews.title": "Customer Reviews",
    "reviews.writeReview": "Write a review",
    "reviews.submitReview": "Submit review",
    "reviews.noReviews": "No reviews yet. Be the first!",
    "reviews.loginToReview": "Log in to leave a review",
    "reviews.placeholder": "Share your experience...",
    "cart.title": "Cart",
    "cart.empty": "Your cart is empty",
    "cart.browseCatalog": "Browse catalog",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.free": "Free",
    "cart.total": "Total",
    "cart.checkout": "Checkout",
    "cart.clear": "Clear cart",
    "checkout.title": "Complete your order",
    "checkout.backToCart": "Back to cart",
    "checkout.paymentMethod": "Payment method",
    "checkout.paymentProof": "Payment proof",
    "checkout.uploadProof": "Click or drag the receipt here",
    "checkout.uploadFormat": "PNG, JPG or PDF (max 5 MB)",
    "checkout.notes": "Notes (optional)",
    "checkout.notesPlaceholder": "Additional information...",
    "checkout.summary": "Summary",
    "checkout.discount": "Discount",
    "checkout.confirm": "Confirm order",
    "checkout.sending": "Sending...",
    "checkout.deliveryNote": "Instant delivery after payment verification",
    "checkout.success": "Order confirmed!",
    "checkout.successDesc": "Your order has been sent successfully. We will verify your payment and deliver your products.",
    "checkout.successEmail": "You will receive your credentials by email once payment is verified.",
    "checkout.continueShopping": "Continue shopping",
    "footer.desc": "Your digital game store in Morocco. Accounts, keys and gift cards for all platforms.",
    "footer.navigation": "Navigation",
    "footer.platforms": "Platforms",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "orders.title": "My Orders",
    "orders.noOrders": "No orders yet",
    "orders.discoverCatalog": "Discover catalog",
    "orders.orderFrom": "Order from",
    "orders.payment": "Payment",
    "orders.code": "Code",
    "orders.pending": "Pending",
    "orders.confirmed": "Confirmed",
    "orders.delivered": "Delivered",
    "orders.cancelled": "Cancelled",
    "auth.back": "Back",
    "common.back": "Back",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.catalog": "المتجر",
    "nav.accounts": "الحسابات",
    "nav.giftCards": "بطاقات الهدايا",
    "nav.login": "تسجيل الدخول",
    "nav.logout": "تسجيل الخروج",
    "nav.myOrders": "طلباتي",
    "nav.admin": "الإدارة",
    "home.instantDelivery": "توصيل فوري",
    "home.instantDeliveryDesc": "استلم منتجك في دقائق",
    "home.securePayment": "دفع آمن",
    "home.securePaymentDesc": "وفاكاش، كاش بلس، تحويل بنكي",
    "home.support247": "دعم 24/7",
    "home.support247Desc": "مساعدة عبر واتساب وتلغرام",
    "home.categories": "الأقسام",
    "home.trending": "🔥 الرائجة",
    "home.bestSellers": "⭐ الأكثر مبيعاً",
    "home.viewAll": "عرض الكل",
    "home.joinTitle": "انضم إلى Zuoss Shop",
    "home.joinDesc": "أنشئ حسابك واستفد من عروضنا الحصرية على الألعاب الرقمية في المغرب.",
    "home.exploreCatalog": "تصفح المتجر",
    "catalog.title": "المتجر",
    "catalog.subtitle": "اكتشف ألعابنا ومنتجاتنا الرقمية",
    "catalog.search": "ابحث عن لعبة...",
    "catalog.filters": "فلترة",
    "catalog.platform": "المنصة",
    "catalog.category": "الفئة",
    "catalog.price": "السعر",
    "catalog.clearFilters": "مسح الفلاتر",
    "catalog.results": "نتيجة",
    "catalog.noProducts": "لم يتم العثور على منتجات",
    "catalog.resetFilters": "إعادة تعيين الفلاتر",
    "catalog.sortBy": "ترتيب حسب",
    "catalog.sortDefault": "الافتراضي",
    "catalog.sortPriceLow": "السعر: من الأقل",
    "catalog.sortPriceHigh": "السعر: من الأعلى",
    "catalog.sortRating": "الأعلى تقييماً",
    "catalog.sortNewest": "الأحدث",
    "catalog.inStockOnly": "المتوفر فقط",
    "product.back": "العودة للمتجر",
    "product.notFound": "المنتج غير موجود",
    "product.loading": "جاري التحميل...",
    "product.type": "النوع",
    "product.delivery": "التوصيل",
    "product.stock": "المخزون",
    "product.inStock": "متوفر",
    "product.outOfStock": "غير متوفر",
    "product.instant": "فوري",
    "product.addToCart": "أضف للسلة",
    "product.addedToCart": "تمت الإضافة",
    "product.instructions": "📋 التعليمات",
    "product.relatedProducts": "منتجات مشابهة",
    "product.reviews": "تقييم",
    "product.account": "حساب كامل",
    "product.key": "مفتاح تفعيل",
    "reviews.title": "تقييمات العملاء",
    "reviews.writeReview": "اكتب تقييماً",
    "reviews.submitReview": "نشر التقييم",
    "reviews.noReviews": "لا توجد تقييمات بعد. كن الأول!",
    "reviews.loginToReview": "سجل دخولك لترك تقييم",
    "reviews.placeholder": "شارك تجربتك...",
    "cart.title": "السلة",
    "cart.empty": "سلتك فارغة",
    "cart.browseCatalog": "تصفح المتجر",
    "cart.subtotal": "المجموع الفرعي",
    "cart.shipping": "الشحن",
    "cart.free": "مجاني",
    "cart.total": "المجموع",
    "cart.checkout": "إتمام الطلب",
    "cart.clear": "تفريغ السلة",
    "checkout.title": "إتمام الطلب",
    "checkout.backToCart": "العودة للسلة",
    "checkout.paymentMethod": "طريقة الدفع",
    "checkout.paymentProof": "إثبات الدفع",
    "checkout.uploadProof": "انقر أو اسحب الإيصال هنا",
    "checkout.uploadFormat": "PNG أو JPG أو PDF (حد أقصى 5 ميجا)",
    "checkout.notes": "ملاحظات (اختياري)",
    "checkout.notesPlaceholder": "معلومات إضافية...",
    "checkout.summary": "الملخص",
    "checkout.discount": "الخصم",
    "checkout.confirm": "تأكيد الطلب",
    "checkout.sending": "جاري الإرسال...",
    "checkout.deliveryNote": "توصيل فوري بعد التحقق من الدفع",
    "checkout.success": "تم تأكيد الطلب!",
    "checkout.successDesc": "تم إرسال طلبك بنجاح. سنتحقق من الدفع ونقوم بتسليم منتجاتك.",
    "checkout.successEmail": "ستتلقى بياناتك عبر البريد الإلكتروني بعد التحقق من الدفع.",
    "checkout.continueShopping": "متابعة التسوق",
    "footer.desc": "متجرك للألعاب الرقمية في المغرب. حسابات ومفاتيح وبطاقات هدايا لجميع المنصات.",
    "footer.navigation": "التنقل",
    "footer.platforms": "المنصات",
    "footer.contact": "التواصل",
    "footer.rights": "جميع الحقوق محفوظة.",
    "orders.title": "طلباتي",
    "orders.noOrders": "لا توجد طلبات حتى الآن",
    "orders.discoverCatalog": "تصفح المتجر",
    "orders.orderFrom": "طلب بتاريخ",
    "orders.payment": "الدفع",
    "orders.code": "كود",
    "orders.pending": "قيد الانتظار",
    "orders.confirmed": "مؤكد",
    "orders.delivered": "تم التسليم",
    "orders.cancelled": "ملغي",
    "auth.back": "رجوع",
    "common.back": "رجوع",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("zuoss-lang");
    return (saved as Lang) || "fr";
  });

  const setLang = useCallback((l: Lang) => {
    setLangState(l);
    localStorage.setItem("zuoss-lang", l);
    document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = l;
  }, []);

  const t = useCallback((key: string) => translations[lang][key] || key, [lang]);
  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
